// Generated by CoffeeScript 1.12.2
(function() {
  var App, dragging;

  App = {};

  dragging = false;


  /*
  	Init
   */

  App.init = function() {
    App.canvas = document.createElement('canvas');
    App.canvas.height = 400;
    App.canvas.width = $('.canvas-container').width();
    document.querySelector('div.canvas-container').appendChild(App.canvas);
    App.ctx = App.canvas.getContext("2d");
    App.ctx.fillStyle = "solid";
    App.ctx.strokeStyle = "#bada55";
    App.ctx.lineWidth = 5;
    App.ctx.lineCap = "round";
    App.clear = function() {
      return App.ctx.clearRect(0, 0, App.canvas.width, App.canvas.height);
    };
    App.draw = function(x, y, type) {
      if (type === "dragstart") {
        App.ctx.beginPath();
        return App.ctx.moveTo(x, y);
      } else if (type === "drag") {
        App.ctx.lineTo(x, y);
        return App.ctx.stroke();
      } else {
        return App.ctx.closePath();
      }
    };
  };

  App.socket = io.connect('http://sr-94933.onmodulus.net:3000');

  App.socket.on('draw', function(data) {
    return App.draw(data.x, data.y, data.type);
  });

  App.init();

  $('canvas').on('mousemove', function(e) {
    var offset, x, y;
    if (dragging) {
      offset = $(this).offset();
      e.offsetX = e.pageX - offset.left;
      e.offsetY = e.pageY - offset.top;
      x = e.offsetX;
      y = e.offsetY;
      App.draw(x, y, 'drag');
      App.socket.emit('drawClick', {
        x: x,
        y: y,
        type: 'drag'
      });
    }
  });

  $('canvas').on('mousedown', function(e) {
    var offset, x, y;
    offset = $(this).offset();
    e.offsetX = e.pageX - offset.left;
    e.offsetY = e.pageY - offset.top;
    x = e.offsetX;
    y = e.offsetY;
    App.draw(x, y, 'dragstart');
    App.socket.emit('drawClick', {
      x: x,
      y: y,
      type: 'dragstart'
    });
    return dragging = true;
  });

  $('canvas').on('mouseup', function(e) {
    var offset, x, y;
    offset = $(this).offset();
    e.offsetX = e.pageX - offset.left;
    e.offsetY = e.pageY - offset.top;
    x = e.offsetX;
    y = e.offsetY;
    App.draw(x, y, 'dragend');
    App.socket.emit('drawClick', {
      x: x,
      y: y,
      type: 'dragend'
    });
    return dragging = false;
  });

  $('#clear').on('click', function(e) {
    return App.clear();
  });

}).call(this);

//# sourceMappingURL=scripts.js.map
